title: Neurobiology of Autism

#remote_theme: pages-themes/midnight@v0.2.0
# remote_theme: abhinavs/moonwalk
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
show_downloads: false

url: https://neurobiology-of-autism.github.io/ # root address of the site
description: > # description of the site (multiple lines allowed)
  Notes about the Neurobiology of Autism

highlighter: rouge

sass:
  style: :compressed

defaults:
  # Academic article
  - scope:
      path: "_posts/article"
      type: posts
    values:
      permalink: article/:title  
  # Academic article
  - scope:
      path: "articles"
      type: posts
    values:
      permalink: articles/:title
  # Hypothesis
  - scope:
      path: "_posts/hypothesis"
      type: posts
    values:
      permalink: hypothesis/:title
  # Phenotype
  - scope:
      path: "_posts/phenotype"
      type: posts
    values:
      permalink: phenotype/:title
